apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin-redis
    purpose: key-value-store
  name: spin-redis
  namespace: '${parameters.namespace}'
spec:
  ports:
  - name: http
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: spin-redis
    purpose: key-value-store
  type: ClusterIP