apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spin-sa-cluster-role
  namespace: '${parameters.namespace}'
  labels:
    purpose: service-account
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - /metrics
    verbs:
      - get