apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-client
    purpose: tools
  name: mysql-client
  namespace: '${parameters.namespace}'
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mysql-client
      purpose: tools
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql-client
        purpose: tools
    spec:
      containers:
        - command:
            - tail
            - -f
            - /dev/null
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          name: mysql-client
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30