apiVersion: v1
kind: ConfigMap
metadata:
  name: spin-mysql-init
  namespace: '${parameters.namespace}'
  labels:
    app: spin-mysql
    purpose: database
    stage: init
  annotations:
    strategy.spinnaker.io/versioned: 'false'
data:
  initdb.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';
    CREATE SCHEMA IF NOT EXISTS clouddriver DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS 'clouddriver_service'@'%' IDENTIFIED BY '${parameters.spin_password}';
    CREATE USER IF NOT EXISTS 'clouddriver_migrate'@'%' IDENTIFIED BY '${parameters.spin_password}';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, EXECUTE, SHOW VIEW ON clouddriver.* TO 'clouddriver_service'@'%';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, SHOW VIEW ON clouddriver.* TO clouddriver_migrate@'%';
    CREATE SCHEMA IF NOT EXISTS orca DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS 'orca_service'@'%' IDENTIFIED BY '${parameters.spin_password}';
    CREATE USER IF NOT EXISTS 'orca_migrate'@'%' IDENTIFIED BY '${parameters.spin_password}';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, EXECUTE, SHOW VIEW ON orca.* TO 'orca_service'@'%';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, SHOW VIEW ON orca.* TO orca_migrate@'%';
    CREATE SCHEMA IF NOT EXISTS front50 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS 'front50_service'@'%' IDENTIFIED BY '${parameters.spin_password}';
    CREATE USER IF NOT EXISTS 'front50_migrate'@'%' IDENTIFIED BY '${parameters.spin_password}';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, EXECUTE, SHOW VIEW ON front50.* TO 'front50_service'@'%';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, SHOW VIEW ON front50.* TO front50_migrate@'%';
    CREATE SCHEMA IF NOT EXISTS fiat DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
    CREATE USER IF NOT EXISTS 'fiat_service'@'%' IDENTIFIED BY '${parameters.spin_password}';
    CREATE USER IF NOT EXISTS 'fiat_migrate'@'%' IDENTIFIED BY '${parameters.spin_password}';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, EXECUTE, SHOW VIEW ON fiat.* TO 'fiat_service'@'%';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, LOCK TABLES, EXECUTE, SHOW VIEW ON fiat.* TO fiat_migrate@'%';