apiVersion: v1
kind: Service
metadata:
  name: spin-mysql
  namespace: '${parameters.namespace}'
  labels:
    app: spin-mysql
    purpose: database
spec:
  ports:
  - port: 3306
  selector:
    app: spin-mysql
    purpose: database
  type: ClusterIP